name: soknad-kontantstotte-api
team: team-soknad
image: repo.adeo.no:5443/soknad/soknad-kontantstotte-api
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
resources:
  limits:
    cpu: 3
healthcheck:
  liveness:
    initialDelay: 20
    path: /api/status/isAlive
  readiness:
    initialDelay: 20
    path: /api/status/isAlive
ingress:
  enabled: true
prometheus:
  enabled: true
  path: /actuator/prometheus
fasitResources:
  used:
# Unleash
  - alias: unleash-api
    resourceType: restservice
# Appdynamics
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: aad_b2c_clientid
    resourceType: credential
    propertyMap:
      username: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_ACCEPTEDAUDIENCE
  - alias: aad_b2c_discovery
    resourceType: baseurl
    propertyMap:
      url: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
  - alias: appres.cms
    resourceType: baseUrl
  - alias: soknad-kontantstotte-proxy-api
    resourceType: restservice
  - alias: soknad-pdf-generator
    resourceType: restservice
  - alias: pdf-gen
    resourceType: restservice
  - alias: soknad-kontantstotte-api-soknad-kontantstotte-proxy-api-apiKey
    resourceType: credential